export default {
  'learn/Canvas/(.*)': 'Canvas/(.*)',
  'learn/CSS/(.*)': 'CSS/(.*)',
  'learn/CSS/效果提升/(.*)': 'CSS/效果提升/(.*)',
  'learn/CSS/知识拓展/(.*)': 'CSS/知识拓展/(.*)',
  'learn/Javascript/webapi/(.*)': 'Javascript_webapi/(.*)',
  'learn/Javascript/(.*)': 'Javascript/(.*)',
  'learn/Git/实战训练/(.*)': 'Git/实战训练/(.*)',
  'learn/Git/潜在的BUG/(.*)': 'Git/潜在的BUG/(.*)',
  'learn/Reg/knowledge/(.*)': 'Reg/knowledge/(.*)',
  'learn/Reg/do/(.*)': 'Reg/do/(.*)',
  'learn/Reg/BUG/(.*)': 'Reg/BUG/(.*)',
  'learn/vue2/(.*)': 'vue2/(.*)',
  'learn/Vue3/(.*)': 'Vue3/(.*)',
  'learn/React/(.*)': 'React/(.*)',
  'learn/TypeScript/(.*)': 'TypeScript/(.*)',
  'learn/Node/(.*)': 'TypeScript/(.*)',
  'learn/study/(.*)': 'study/(.*)',
  'project/lingsi/(.*)': 'lingsi/(.*)',
  'project/tydumpling/(.*)': 'tydumpling/(.*)',
  'project/baidu/(.*)': 'baidu/(.*)',
  'project/myself/(.*)': 'myself/(.*)',
}
